/********************************************************************************
** Form generated from reading UI file 'secdialog.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SECDIALOG_H
#define UI_SECDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_secDialog
{
public:
    QHBoxLayout *horizontalLayout_2;
    QStackedWidget *stackedWidgetmain;
    QWidget *MainMenu;
    QLabel *sectitle;
    QLabel *label;
    QPushButton *reservation;
    QPushButton *FlightDetails;
    QPushButton *CancelFlight;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QWidget *Reserveclick;
    QLabel *title;
    QLabel *Resevationlable;
    QLabel *Text;
    QComboBox *comboBox;
    QLabel *Departurelabel;
    QLabel *Arrivallable;
    QLabel *Datelabel;
    QLabel *Timelable;
    QLineEdit *Dinput;
    QLineEdit *Ainput;
    QLineEdit *dateinput;
    QLineEdit *timeinput;
    QPushButton *Backmenu;
    QPushButton *Next;
    QComboBox *comboBoxclass;
    QLabel *label_2;
    QLabel *TicketNimber;
    QLineEdit *TicketNo;
    QWidget *Reservation_2;
    QLabel *titlelable;
    QLabel *Reservationlable;
    QLabel *Namelabel;
    QLabel *emaillable;
    QLabel *passportlabel;
    QLabel *addresslabel;
    QLabel *numberlabel;
    QLineEdit *Nameinput;
    QLineEdit *Emailinput;
    QLineEdit *Passportinput;
    QLineEdit *addressinput;
    QLineEdit *phoneinput;
    QPushButton *Backbutton;
    QPushButton *insertbutton;
    QWidget *flightdetail;
    QLabel *title_2;
    QLabel *detaillable_2;
    QPushButton *fdetails;
    QPushButton *insertflight;
    QPushButton *Backdeatail;
    QWidget *FlightdetailSee;
    QLabel *title_3;
    QLabel *detaillable_3;
    QLabel *label_3;
    QLineEdit *searchflight;
    QPushButton *search;
    QPushButton *back;
    QLineEdit *searchflightname;
    QLineEdit *searchflightnumber;
    QLineEdit *searchflightform;
    QLineEdit *searchflightTo;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLineEdit *searchflighttime;
    QWidget *Insert;
    QLabel *title_4;
    QLineEdit *FormSave;
    QLineEdit *NameSave;
    QLabel *time;
    QLineEdit *NumberSave;
    QLabel *fnumber;
    QLineEdit *TimeSave;
    QLabel *form;
    QLabel *to;
    QLabel *detaillable_4;
    QPushButton *back_2;
    QLineEdit *TOSave;
    QLabel *fname;
    QLabel *detaillable_5;
    QPushButton *back_3;
    QWidget *Delete;
    QLabel *detaillable_6;
    QLabel *Title5;
    QLabel *MiniTitle;
    QLineEdit *Inputsss;
    QPushButton *Search;
    QLabel *Ticket;
    QLineEdit *Ticketinput;
    QLineEdit *CNameinput;
    QLabel *CName;
    QLineEdit *CEmailinput;
    QLabel *CEmail;
    QLineEdit *CPassportInput;
    QLabel *CPassport;
    QLabel *label_13;
    QLabel *CAddress;
    QLineEdit *CPhoneInput;
    QLabel *CPhone;
    QLineEdit *CAddressInput;
    QLabel *CArrrival;
    QLabel *CTIme;
    QLabel *Cdeparture;
    QLineEdit *CArrrivalInput;
    QLineEdit *CTImeInput;
    QLineEdit *CdepartureInput;
    QPushButton *Deletecancel;
    QLineEdit *Cdateinput;
    QLabel *CDate;
    QPushButton *Back;
    QWidget *TicketRecipt;
    QLabel *detaillable_7;
    QLabel *Title5_2;
    QLabel *SearchReceipt;
    QLineEdit *SearchReciptInput;
    QLabel *ticketl;
    QLineEdit *TicketRInput;
    QLabel *Namel;
    QLineEdit *NameRinput;
    QLabel *Arrivel;
    QLineEdit *ArrivedSinput;
    QLabel *TimeL;
    QLineEdit *TimeSinput;
    QLabel *departureL;
    QLineEdit *DepartureSinput;
    QLabel *DateL;
    QLineEdit *DateSinput;
    QLineEdit *AmountShow;
    QLabel *AmountL;
    QPushButton *Search_2;
    QPushButton *Print;
    QPushButton *BackR;

    void setupUi(QDialog *secDialog)
    {
        if (secDialog->objectName().isEmpty())
            secDialog->setObjectName(QStringLiteral("secDialog"));
        secDialog->resize(652, 486);
        secDialog->setStyleSheet(QStringLiteral("background-image: url(:/resources/img/Simple.jpg);"));
        horizontalLayout_2 = new QHBoxLayout(secDialog);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        stackedWidgetmain = new QStackedWidget(secDialog);
        stackedWidgetmain->setObjectName(QStringLiteral("stackedWidgetmain"));
        stackedWidgetmain->setEnabled(true);
        stackedWidgetmain->setAutoFillBackground(false);
        stackedWidgetmain->setFrameShape(QFrame::Box);
        stackedWidgetmain->setFrameShadow(QFrame::Sunken);
        stackedWidgetmain->setLineWidth(3);
        stackedWidgetmain->setMidLineWidth(5);
        MainMenu = new QWidget();
        MainMenu->setObjectName(QStringLiteral("MainMenu"));
        sectitle = new QLabel(MainMenu);
        sectitle->setObjectName(QStringLiteral("sectitle"));
        sectitle->setGeometry(QRect(10, 20, 521, 41));
        QFont font;
        font.setPointSize(24);
        font.setBold(true);
        font.setItalic(true);
        font.setWeight(75);
        sectitle->setFont(font);
        label = new QLabel(MainMenu);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 75, 131, 31));
        QFont font1;
        font1.setFamily(QStringLiteral("Times New Roman"));
        font1.setPointSize(13);
        font1.setBold(false);
        font1.setItalic(true);
        font1.setUnderline(true);
        font1.setWeight(9);
        label->setFont(font1);
        label->setStyleSheet(QLatin1String("text-shadow: 2px 2px 2px #1C6EA4;\n"
"text-decoration: underline;\n"
"font: 75 italic 13pt \"Times New Roman\";"));
        reservation = new QPushButton(MainMenu);
        reservation->setObjectName(QStringLiteral("reservation"));
        reservation->setGeometry(QRect(0, 120, 130, 30));
        reservation->setStyleSheet(QLatin1String("text-shadow: 2px 2px 2px #1C6EA4;\n"
"text-decoration: underline;\n"
"font: 75 italic 13pt \"Times New Roman\";"));
        FlightDetails = new QPushButton(MainMenu);
        FlightDetails->setObjectName(QStringLiteral("FlightDetails"));
        FlightDetails->setGeometry(QRect(0, 160, 130, 30));
        FlightDetails->setStyleSheet(QLatin1String("text-shadow: 2px 2px 2px #1C6EA4;\n"
"text-decoration: underline;\n"
"font: 75 italic 13pt \"Times New Roman\";"));
        CancelFlight = new QPushButton(MainMenu);
        CancelFlight->setObjectName(QStringLiteral("CancelFlight"));
        CancelFlight->setGeometry(QRect(0, 200, 130, 30));
        CancelFlight->setStyleSheet(QLatin1String("text-shadow: 2px 2px 2px #1C6EA4;\n"
"text-decoration: underline;\n"
"font: 75 italic 13pt \"Times New Roman\";"));
        pushButton_4 = new QPushButton(MainMenu);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(0, 240, 130, 30));
        pushButton_4->setStyleSheet(QLatin1String("text-shadow: 2px 2px 2px #1C6EA4;\n"
"text-decoration: underline;\n"
"font: 75 italic 13pt \"Times New Roman\";"));
        pushButton_5 = new QPushButton(MainMenu);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(0, 280, 130, 30));
        pushButton_5->setStyleSheet(QLatin1String("text-shadow: 2px 2px 2px #1C6EA4;\n"
"text-decoration: underline;\n"
"font: 75 italic 13pt \"Times New Roman\";"));
        stackedWidgetmain->addWidget(MainMenu);
        Reserveclick = new QWidget();
        Reserveclick->setObjectName(QStringLiteral("Reserveclick"));
        title = new QLabel(Reserveclick);
        title->setObjectName(QStringLiteral("title"));
        title->setGeometry(QRect(90, 20, 441, 31));
        title->setStyleSheet(QLatin1String("font: 75 italic 20pt \"MS Shell Dlg 2\";\n"
"font: 75 22pt \"MS Shell Dlg 2\";"));
        Resevationlable = new QLabel(Reserveclick);
        Resevationlable->setObjectName(QStringLiteral("Resevationlable"));
        Resevationlable->setGeometry(QRect(190, 75, 100, 21));
        Resevationlable->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        Text = new QLabel(Reserveclick);
        Text->setObjectName(QStringLiteral("Text"));
        Text->setGeometry(QRect(80, 120, 310, 21));
        Text->setStyleSheet(QStringLiteral("font: 75 11pt \"MS Shell Dlg 2\";"));
        comboBox = new QComboBox(Reserveclick);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(80, 140, 271, 29));
        Departurelabel = new QLabel(Reserveclick);
        Departurelabel->setObjectName(QStringLiteral("Departurelabel"));
        Departurelabel->setGeometry(QRect(80, 210, 110, 28));
        Departurelabel->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        Arrivallable = new QLabel(Reserveclick);
        Arrivallable->setObjectName(QStringLiteral("Arrivallable"));
        Arrivallable->setGeometry(QRect(80, 240, 110, 27));
        Arrivallable->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        Datelabel = new QLabel(Reserveclick);
        Datelabel->setObjectName(QStringLiteral("Datelabel"));
        Datelabel->setGeometry(QRect(80, 270, 110, 27));
        Datelabel->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        Timelable = new QLabel(Reserveclick);
        Timelable->setObjectName(QStringLiteral("Timelable"));
        Timelable->setGeometry(QRect(80, 300, 110, 27));
        Timelable->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        Dinput = new QLineEdit(Reserveclick);
        Dinput->setObjectName(QStringLiteral("Dinput"));
        Dinput->setGeometry(QRect(190, 210, 140, 27));
        Ainput = new QLineEdit(Reserveclick);
        Ainput->setObjectName(QStringLiteral("Ainput"));
        Ainput->setGeometry(QRect(190, 240, 140, 27));
        dateinput = new QLineEdit(Reserveclick);
        dateinput->setObjectName(QStringLiteral("dateinput"));
        dateinput->setGeometry(QRect(190, 270, 140, 27));
        timeinput = new QLineEdit(Reserveclick);
        timeinput->setObjectName(QStringLiteral("timeinput"));
        timeinput->setGeometry(QRect(190, 300, 140, 27));
        Backmenu = new QPushButton(Reserveclick);
        Backmenu->setObjectName(QStringLiteral("Backmenu"));
        Backmenu->setGeometry(QRect(130, 370, 90, 30));
        Backmenu->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        Next = new QPushButton(Reserveclick);
        Next->setObjectName(QStringLiteral("Next"));
        Next->setGeometry(QRect(230, 370, 100, 30));
        Next->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        comboBoxclass = new QComboBox(Reserveclick);
        comboBoxclass->setObjectName(QStringLiteral("comboBoxclass"));
        comboBoxclass->setGeometry(QRect(220, 330, 130, 29));
        label_2 = new QLabel(Reserveclick);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(80, 330, 110, 27));
        label_2->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        TicketNimber = new QLabel(Reserveclick);
        TicketNimber->setObjectName(QStringLiteral("TicketNimber"));
        TicketNimber->setGeometry(QRect(80, 180, 110, 30));
        TicketNimber->setStyleSheet(QStringLiteral("font: 75 11pt \"Times New Roman\";"));
        TicketNo = new QLineEdit(Reserveclick);
        TicketNo->setObjectName(QStringLiteral("TicketNo"));
        TicketNo->setGeometry(QRect(190, 180, 140, 30));
        stackedWidgetmain->addWidget(Reserveclick);
        Reservation_2 = new QWidget();
        Reservation_2->setObjectName(QStringLiteral("Reservation_2"));
        titlelable = new QLabel(Reservation_2);
        titlelable->setObjectName(QStringLiteral("titlelable"));
        titlelable->setGeometry(QRect(70, 10, 420, 40));
        titlelable->setStyleSheet(QStringLiteral("font: 75 20pt \"MS Shell Dlg 2\";"));
        Reservationlable = new QLabel(Reservation_2);
        Reservationlable->setObjectName(QStringLiteral("Reservationlable"));
        Reservationlable->setGeometry(QRect(180, 60, 110, 20));
        Reservationlable->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        Namelabel = new QLabel(Reservation_2);
        Namelabel->setObjectName(QStringLiteral("Namelabel"));
        Namelabel->setGeometry(QRect(100, 120, 130, 20));
        Namelabel->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        emaillable = new QLabel(Reservation_2);
        emaillable->setObjectName(QStringLiteral("emaillable"));
        emaillable->setGeometry(QRect(100, 150, 130, 20));
        emaillable->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        passportlabel = new QLabel(Reservation_2);
        passportlabel->setObjectName(QStringLiteral("passportlabel"));
        passportlabel->setGeometry(QRect(100, 180, 130, 20));
        passportlabel->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        addresslabel = new QLabel(Reservation_2);
        addresslabel->setObjectName(QStringLiteral("addresslabel"));
        addresslabel->setGeometry(QRect(100, 210, 130, 20));
        addresslabel->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        numberlabel = new QLabel(Reservation_2);
        numberlabel->setObjectName(QStringLiteral("numberlabel"));
        numberlabel->setGeometry(QRect(100, 240, 130, 20));
        numberlabel->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        Nameinput = new QLineEdit(Reservation_2);
        Nameinput->setObjectName(QStringLiteral("Nameinput"));
        Nameinput->setGeometry(QRect(230, 120, 180, 20));
        Emailinput = new QLineEdit(Reservation_2);
        Emailinput->setObjectName(QStringLiteral("Emailinput"));
        Emailinput->setGeometry(QRect(230, 150, 180, 20));
        Passportinput = new QLineEdit(Reservation_2);
        Passportinput->setObjectName(QStringLiteral("Passportinput"));
        Passportinput->setGeometry(QRect(230, 180, 180, 20));
        addressinput = new QLineEdit(Reservation_2);
        addressinput->setObjectName(QStringLiteral("addressinput"));
        addressinput->setGeometry(QRect(230, 210, 180, 20));
        phoneinput = new QLineEdit(Reservation_2);
        phoneinput->setObjectName(QStringLiteral("phoneinput"));
        phoneinput->setGeometry(QRect(230, 240, 180, 20));
        Backbutton = new QPushButton(Reservation_2);
        Backbutton->setObjectName(QStringLiteral("Backbutton"));
        Backbutton->setGeometry(QRect(210, 280, 90, 23));
        Backbutton->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        insertbutton = new QPushButton(Reservation_2);
        insertbutton->setObjectName(QStringLiteral("insertbutton"));
        insertbutton->setGeometry(QRect(310, 280, 100, 23));
        insertbutton->setStyleSheet(QStringLiteral("font: 75 13pt \"Times New Roman\";"));
        stackedWidgetmain->addWidget(Reservation_2);
        flightdetail = new QWidget();
        flightdetail->setObjectName(QStringLiteral("flightdetail"));
        title_2 = new QLabel(flightdetail);
        title_2->setObjectName(QStringLiteral("title_2"));
        title_2->setGeometry(QRect(90, 10, 441, 31));
        title_2->setStyleSheet(QLatin1String("font: 75 italic 20pt \"MS Shell Dlg 2\";\n"
"font: 75 22pt \"MS Shell Dlg 2\";"));
        detaillable_2 = new QLabel(flightdetail);
        detaillable_2->setObjectName(QStringLiteral("detaillable_2"));
        detaillable_2->setGeometry(QRect(190, 70, 191, 20));
        detaillable_2->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        fdetails = new QPushButton(flightdetail);
        fdetails->setObjectName(QStringLiteral("fdetails"));
        fdetails->setGeometry(QRect(190, 150, 190, 30));
        fdetails->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        insertflight = new QPushButton(flightdetail);
        insertflight->setObjectName(QStringLiteral("insertflight"));
        insertflight->setGeometry(QRect(190, 190, 190, 30));
        insertflight->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        Backdeatail = new QPushButton(flightdetail);
        Backdeatail->setObjectName(QStringLiteral("Backdeatail"));
        Backdeatail->setGeometry(QRect(30, 290, 75, 23));
        Backdeatail->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        stackedWidgetmain->addWidget(flightdetail);
        FlightdetailSee = new QWidget();
        FlightdetailSee->setObjectName(QStringLiteral("FlightdetailSee"));
        title_3 = new QLabel(FlightdetailSee);
        title_3->setObjectName(QStringLiteral("title_3"));
        title_3->setGeometry(QRect(110, 20, 441, 31));
        title_3->setStyleSheet(QLatin1String("font: 75 italic 20pt \"MS Shell Dlg 2\";\n"
"font: 75 22pt \"MS Shell Dlg 2\";"));
        detaillable_3 = new QLabel(FlightdetailSee);
        detaillable_3->setObjectName(QStringLiteral("detaillable_3"));
        detaillable_3->setGeometry(QRect(190, 60, 191, 20));
        detaillable_3->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        label_3 = new QLabel(FlightdetailSee);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(50, 130, 190, 30));
        label_3->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        searchflight = new QLineEdit(FlightdetailSee);
        searchflight->setObjectName(QStringLiteral("searchflight"));
        searchflight->setGeometry(QRect(240, 130, 230, 30));
        search = new QPushButton(FlightdetailSee);
        search->setObjectName(QStringLiteral("search"));
        search->setGeometry(QRect(300, 160, 120, 23));
        search->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        back = new QPushButton(FlightdetailSee);
        back->setObjectName(QStringLiteral("back"));
        back->setGeometry(QRect(240, 380, 110, 30));
        back->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        searchflightname = new QLineEdit(FlightdetailSee);
        searchflightname->setObjectName(QStringLiteral("searchflightname"));
        searchflightname->setGeometry(QRect(180, 200, 170, 30));
        searchflightnumber = new QLineEdit(FlightdetailSee);
        searchflightnumber->setObjectName(QStringLiteral("searchflightnumber"));
        searchflightnumber->setGeometry(QRect(180, 230, 170, 30));
        searchflightform = new QLineEdit(FlightdetailSee);
        searchflightform->setObjectName(QStringLiteral("searchflightform"));
        searchflightform->setGeometry(QRect(180, 260, 170, 30));
        searchflightTo = new QLineEdit(FlightdetailSee);
        searchflightTo->setObjectName(QStringLiteral("searchflightTo"));
        searchflightTo->setGeometry(QRect(180, 290, 170, 30));
        label_4 = new QLabel(FlightdetailSee);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(50, 200, 130, 30));
        label_4->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        label_5 = new QLabel(FlightdetailSee);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 230, 130, 30));
        label_5->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        label_6 = new QLabel(FlightdetailSee);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(50, 260, 130, 30));
        label_6->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        label_7 = new QLabel(FlightdetailSee);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(50, 290, 130, 30));
        label_7->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        label_8 = new QLabel(FlightdetailSee);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(50, 320, 130, 30));
        label_8->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        searchflighttime = new QLineEdit(FlightdetailSee);
        searchflighttime->setObjectName(QStringLiteral("searchflighttime"));
        searchflighttime->setGeometry(QRect(180, 320, 170, 30));
        stackedWidgetmain->addWidget(FlightdetailSee);
        title_3->raise();
        detaillable_3->raise();
        label_3->raise();
        searchflight->raise();
        search->raise();
        searchflightname->raise();
        searchflightnumber->raise();
        searchflightform->raise();
        searchflightTo->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        searchflighttime->raise();
        back->raise();
        Insert = new QWidget();
        Insert->setObjectName(QStringLiteral("Insert"));
        title_4 = new QLabel(Insert);
        title_4->setObjectName(QStringLiteral("title_4"));
        title_4->setGeometry(QRect(110, 20, 441, 31));
        title_4->setStyleSheet(QLatin1String("font: 75 italic 20pt \"MS Shell Dlg 2\";\n"
"font: 75 22pt \"MS Shell Dlg 2\";"));
        FormSave = new QLineEdit(Insert);
        FormSave->setObjectName(QStringLiteral("FormSave"));
        FormSave->setGeometry(QRect(240, 220, 170, 30));
        NameSave = new QLineEdit(Insert);
        NameSave->setObjectName(QStringLiteral("NameSave"));
        NameSave->setGeometry(QRect(240, 160, 170, 30));
        time = new QLabel(Insert);
        time->setObjectName(QStringLiteral("time"));
        time->setGeometry(QRect(110, 280, 130, 30));
        time->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        NumberSave = new QLineEdit(Insert);
        NumberSave->setObjectName(QStringLiteral("NumberSave"));
        NumberSave->setGeometry(QRect(240, 190, 170, 30));
        fnumber = new QLabel(Insert);
        fnumber->setObjectName(QStringLiteral("fnumber"));
        fnumber->setGeometry(QRect(110, 190, 130, 30));
        fnumber->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        TimeSave = new QLineEdit(Insert);
        TimeSave->setObjectName(QStringLiteral("TimeSave"));
        TimeSave->setGeometry(QRect(240, 280, 170, 30));
        form = new QLabel(Insert);
        form->setObjectName(QStringLiteral("form"));
        form->setGeometry(QRect(110, 220, 130, 30));
        form->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        to = new QLabel(Insert);
        to->setObjectName(QStringLiteral("to"));
        to->setGeometry(QRect(110, 250, 130, 30));
        to->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        detaillable_4 = new QLabel(Insert);
        detaillable_4->setObjectName(QStringLiteral("detaillable_4"));
        detaillable_4->setGeometry(QRect(190, 60, 191, 20));
        detaillable_4->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        back_2 = new QPushButton(Insert);
        back_2->setObjectName(QStringLiteral("back_2"));
        back_2->setGeometry(QRect(180, 320, 110, 30));
        back_2->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        TOSave = new QLineEdit(Insert);
        TOSave->setObjectName(QStringLiteral("TOSave"));
        TOSave->setGeometry(QRect(240, 250, 170, 30));
        fname = new QLabel(Insert);
        fname->setObjectName(QStringLiteral("fname"));
        fname->setGeometry(QRect(111, 161, 130, 30));
        fname->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        detaillable_5 = new QLabel(Insert);
        detaillable_5->setObjectName(QStringLiteral("detaillable_5"));
        detaillable_5->setGeometry(QRect(90, 120, 340, 40));
        detaillable_5->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        back_3 = new QPushButton(Insert);
        back_3->setObjectName(QStringLiteral("back_3"));
        back_3->setGeometry(QRect(310, 320, 110, 30));
        back_3->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        stackedWidgetmain->addWidget(Insert);
        Delete = new QWidget();
        Delete->setObjectName(QStringLiteral("Delete"));
        detaillable_6 = new QLabel(Delete);
        detaillable_6->setObjectName(QStringLiteral("detaillable_6"));
        detaillable_6->setGeometry(QRect(170, 60, 191, 31));
        detaillable_6->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        Title5 = new QLabel(Delete);
        Title5->setObjectName(QStringLiteral("Title5"));
        Title5->setGeometry(QRect(90, 20, 441, 31));
        Title5->setStyleSheet(QLatin1String("font: 75 italic 20pt \"MS Shell Dlg 2\";\n"
"font: 75 22pt \"MS Shell Dlg 2\";"));
        MiniTitle = new QLabel(Delete);
        MiniTitle->setObjectName(QStringLiteral("MiniTitle"));
        MiniTitle->setGeometry(QRect(100, 100, 341, 30));
        MiniTitle->setStyleSheet(QStringLiteral("font: 75 12pt \"MS Shell Dlg 2\";"));
        Inputsss = new QLineEdit(Delete);
        Inputsss->setObjectName(QStringLiteral("Inputsss"));
        Inputsss->setGeometry(QRect(100, 130, 240, 30));
        Search = new QPushButton(Delete);
        Search->setObjectName(QStringLiteral("Search"));
        Search->setGeometry(QRect(340, 130, 100, 30));
        Search->setStyleSheet(QStringLiteral("font: 12pt \"Times New Roman\";"));
        Ticket = new QLabel(Delete);
        Ticket->setObjectName(QStringLiteral("Ticket"));
        Ticket->setGeometry(QRect(69, 210, 131, 20));
        Ticket->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        Ticketinput = new QLineEdit(Delete);
        Ticketinput->setObjectName(QStringLiteral("Ticketinput"));
        Ticketinput->setGeometry(QRect(200, 210, 200, 20));
        CNameinput = new QLineEdit(Delete);
        CNameinput->setObjectName(QStringLiteral("CNameinput"));
        CNameinput->setGeometry(QRect(200, 230, 200, 20));
        CName = new QLabel(Delete);
        CName->setObjectName(QStringLiteral("CName"));
        CName->setGeometry(QRect(70, 230, 130, 20));
        CName->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        CEmailinput = new QLineEdit(Delete);
        CEmailinput->setObjectName(QStringLiteral("CEmailinput"));
        CEmailinput->setGeometry(QRect(200, 250, 200, 20));
        CEmail = new QLabel(Delete);
        CEmail->setObjectName(QStringLiteral("CEmail"));
        CEmail->setGeometry(QRect(70, 250, 130, 20));
        CEmail->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        CPassportInput = new QLineEdit(Delete);
        CPassportInput->setObjectName(QStringLiteral("CPassportInput"));
        CPassportInput->setGeometry(QRect(200, 270, 200, 20));
        CPassport = new QLabel(Delete);
        CPassport->setObjectName(QStringLiteral("CPassport"));
        CPassport->setGeometry(QRect(70, 270, 130, 20));
        CPassport->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        label_13 = new QLabel(Delete);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(70, 170, 360, 40));
        label_13->setStyleSheet(QStringLiteral("font: 14pt \"Times New Roman\";"));
        CAddress = new QLabel(Delete);
        CAddress->setObjectName(QStringLiteral("CAddress"));
        CAddress->setGeometry(QRect(70, 310, 130, 20));
        CAddress->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        CPhoneInput = new QLineEdit(Delete);
        CPhoneInput->setObjectName(QStringLiteral("CPhoneInput"));
        CPhoneInput->setGeometry(QRect(200, 290, 200, 20));
        CPhone = new QLabel(Delete);
        CPhone->setObjectName(QStringLiteral("CPhone"));
        CPhone->setGeometry(QRect(70, 290, 130, 20));
        CPhone->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        CAddressInput = new QLineEdit(Delete);
        CAddressInput->setObjectName(QStringLiteral("CAddressInput"));
        CAddressInput->setGeometry(QRect(200, 310, 200, 20));
        CArrrival = new QLabel(Delete);
        CArrrival->setObjectName(QStringLiteral("CArrrival"));
        CArrrival->setGeometry(QRect(70, 370, 130, 20));
        CArrrival->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        CTIme = new QLabel(Delete);
        CTIme->setObjectName(QStringLiteral("CTIme"));
        CTIme->setGeometry(QRect(70, 330, 130, 20));
        CTIme->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        Cdeparture = new QLabel(Delete);
        Cdeparture->setObjectName(QStringLiteral("Cdeparture"));
        Cdeparture->setGeometry(QRect(70, 350, 130, 20));
        Cdeparture->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        CArrrivalInput = new QLineEdit(Delete);
        CArrrivalInput->setObjectName(QStringLiteral("CArrrivalInput"));
        CArrrivalInput->setGeometry(QRect(200, 370, 200, 20));
        CTImeInput = new QLineEdit(Delete);
        CTImeInput->setObjectName(QStringLiteral("CTImeInput"));
        CTImeInput->setGeometry(QRect(200, 330, 200, 20));
        CdepartureInput = new QLineEdit(Delete);
        CdepartureInput->setObjectName(QStringLiteral("CdepartureInput"));
        CdepartureInput->setGeometry(QRect(200, 350, 200, 20));
        Deletecancel = new QPushButton(Delete);
        Deletecancel->setObjectName(QStringLiteral("Deletecancel"));
        Deletecancel->setGeometry(QRect(300, 410, 100, 23));
        Deletecancel->setStyleSheet(QStringLiteral("font: 12pt \"Times New Roman\";"));
        Cdateinput = new QLineEdit(Delete);
        Cdateinput->setObjectName(QStringLiteral("Cdateinput"));
        Cdateinput->setGeometry(QRect(200, 390, 200, 20));
        CDate = new QLabel(Delete);
        CDate->setObjectName(QStringLiteral("CDate"));
        CDate->setGeometry(QRect(70, 390, 130, 20));
        CDate->setStyleSheet(QStringLiteral("font: 75 italic 12pt \"Times New Roman\";"));
        Back = new QPushButton(Delete);
        Back->setObjectName(QStringLiteral("Back"));
        Back->setGeometry(QRect(200, 410, 100, 23));
        Back->setStyleSheet(QStringLiteral("font: 12pt \"Times New Roman\";"));
        stackedWidgetmain->addWidget(Delete);
        detaillable_6->raise();
        Title5->raise();
        MiniTitle->raise();
        Inputsss->raise();
        Search->raise();
        Ticket->raise();
        CNameinput->raise();
        CName->raise();
        CEmailinput->raise();
        CEmail->raise();
        CPassportInput->raise();
        CPassport->raise();
        label_13->raise();
        CAddress->raise();
        CPhoneInput->raise();
        CPhone->raise();
        CAddressInput->raise();
        CArrrival->raise();
        CTIme->raise();
        Cdeparture->raise();
        CArrrivalInput->raise();
        CTImeInput->raise();
        CdepartureInput->raise();
        Deletecancel->raise();
        Ticketinput->raise();
        Cdateinput->raise();
        CDate->raise();
        Back->raise();
        TicketRecipt = new QWidget();
        TicketRecipt->setObjectName(QStringLiteral("TicketRecipt"));
        detaillable_7 = new QLabel(TicketRecipt);
        detaillable_7->setObjectName(QStringLiteral("detaillable_7"));
        detaillable_7->setGeometry(QRect(160, 50, 230, 31));
        detaillable_7->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        Title5_2 = new QLabel(TicketRecipt);
        Title5_2->setObjectName(QStringLiteral("Title5_2"));
        Title5_2->setGeometry(QRect(100, 10, 441, 31));
        Title5_2->setStyleSheet(QLatin1String("font: 75 italic 20pt \"MS Shell Dlg 2\";\n"
"font: 75 22pt \"MS Shell Dlg 2\";"));
        SearchReceipt = new QLabel(TicketRecipt);
        SearchReceipt->setObjectName(QStringLiteral("SearchReceipt"));
        SearchReceipt->setGeometry(QRect(20, 110, 230, 20));
        SearchReceipt->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        SearchReciptInput = new QLineEdit(TicketRecipt);
        SearchReciptInput->setObjectName(QStringLiteral("SearchReciptInput"));
        SearchReciptInput->setGeometry(QRect(250, 110, 180, 20));
        ticketl = new QLabel(TicketRecipt);
        ticketl->setObjectName(QStringLiteral("ticketl"));
        ticketl->setGeometry(QRect(30, 170, 150, 20));
        ticketl->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        TicketRInput = new QLineEdit(TicketRecipt);
        TicketRInput->setObjectName(QStringLiteral("TicketRInput"));
        TicketRInput->setGeometry(QRect(180, 170, 180, 20));
        Namel = new QLabel(TicketRecipt);
        Namel->setObjectName(QStringLiteral("Namel"));
        Namel->setGeometry(QRect(30, 190, 150, 20));
        Namel->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        NameRinput = new QLineEdit(TicketRecipt);
        NameRinput->setObjectName(QStringLiteral("NameRinput"));
        NameRinput->setGeometry(QRect(180, 190, 180, 20));
        Arrivel = new QLabel(TicketRecipt);
        Arrivel->setObjectName(QStringLiteral("Arrivel"));
        Arrivel->setGeometry(QRect(30, 230, 150, 20));
        Arrivel->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        ArrivedSinput = new QLineEdit(TicketRecipt);
        ArrivedSinput->setObjectName(QStringLiteral("ArrivedSinput"));
        ArrivedSinput->setGeometry(QRect(180, 230, 180, 20));
        TimeL = new QLabel(TicketRecipt);
        TimeL->setObjectName(QStringLiteral("TimeL"));
        TimeL->setGeometry(QRect(30, 250, 150, 20));
        TimeL->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        TimeSinput = new QLineEdit(TicketRecipt);
        TimeSinput->setObjectName(QStringLiteral("TimeSinput"));
        TimeSinput->setGeometry(QRect(180, 250, 180, 20));
        departureL = new QLabel(TicketRecipt);
        departureL->setObjectName(QStringLiteral("departureL"));
        departureL->setGeometry(QRect(30, 210, 150, 20));
        departureL->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        DepartureSinput = new QLineEdit(TicketRecipt);
        DepartureSinput->setObjectName(QStringLiteral("DepartureSinput"));
        DepartureSinput->setGeometry(QRect(180, 210, 180, 20));
        DateL = new QLabel(TicketRecipt);
        DateL->setObjectName(QStringLiteral("DateL"));
        DateL->setGeometry(QRect(30, 270, 150, 20));
        DateL->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        DateSinput = new QLineEdit(TicketRecipt);
        DateSinput->setObjectName(QStringLiteral("DateSinput"));
        DateSinput->setGeometry(QRect(180, 270, 180, 20));
        AmountShow = new QLineEdit(TicketRecipt);
        AmountShow->setObjectName(QStringLiteral("AmountShow"));
        AmountShow->setGeometry(QRect(180, 290, 180, 20));
        AmountL = new QLabel(TicketRecipt);
        AmountL->setObjectName(QStringLiteral("AmountL"));
        AmountL->setGeometry(QRect(30, 290, 150, 20));
        AmountL->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        Search_2 = new QPushButton(TicketRecipt);
        Search_2->setObjectName(QStringLiteral("Search_2"));
        Search_2->setGeometry(QRect(430, 110, 80, 20));
        Search_2->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        Print = new QPushButton(TicketRecipt);
        Print->setObjectName(QStringLiteral("Print"));
        Print->setGeometry(QRect(280, 310, 80, 23));
        Print->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        BackR = new QPushButton(TicketRecipt);
        BackR->setObjectName(QStringLiteral("BackR"));
        BackR->setGeometry(QRect(200, 310, 80, 23));
        BackR->setStyleSheet(QLatin1String("\n"
"font: 100 12pt \"Times New Roman\";"));
        stackedWidgetmain->addWidget(TicketRecipt);

        horizontalLayout_2->addWidget(stackedWidgetmain);


        retranslateUi(secDialog);

        stackedWidgetmain->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(secDialog);
    } // setupUi

    void retranslateUi(QDialog *secDialog)
    {
        secDialog->setWindowTitle(QApplication::translate("secDialog", "Dialog", 0));
        sectitle->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        label->setText(QApplication::translate("secDialog", "Categories", 0));
        reservation->setText(QApplication::translate("secDialog", "Reservation", 0));
        FlightDetails->setText(QApplication::translate("secDialog", "Flight Details", 0));
        CancelFlight->setText(QApplication::translate("secDialog", "Cancel Flight", 0));
        pushButton_4->setText(QApplication::translate("secDialog", "Ticket Receipt", 0));
        pushButton_5->setText(QApplication::translate("secDialog", "Exit", 0));
        title->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        Resevationlable->setText(QApplication::translate("secDialog", "Reservation", 0));
        Text->setText(QApplication::translate("secDialog", " How many Seats You Want to Reserve?", 0));
        Departurelabel->setText(QApplication::translate("secDialog", " Departure City", 0));
        Arrivallable->setText(QApplication::translate("secDialog", " Arrival City", 0));
        Datelabel->setText(QApplication::translate("secDialog", " Date", 0));
        Timelable->setText(QApplication::translate("secDialog", " Time", 0));
        Backmenu->setText(QApplication::translate("secDialog", "Back", 0));
        Next->setText(QApplication::translate("secDialog", "Next", 0));
        label_2->setText(QApplication::translate("secDialog", "Choice Class", 0));
        TicketNimber->setText(QApplication::translate("secDialog", "  Ticket No:", 0));
        titlelable->setText(QApplication::translate("secDialog", " WELCOME TO AIRLINE SYSTEM", 0));
        Reservationlable->setText(QApplication::translate("secDialog", "Reservation", 0));
        Namelabel->setText(QApplication::translate("secDialog", "Name", 0));
        emaillable->setText(QApplication::translate("secDialog", "E-mail", 0));
        passportlabel->setText(QApplication::translate("secDialog", "Pass PortNumber", 0));
        addresslabel->setText(QApplication::translate("secDialog", "Address", 0));
        numberlabel->setText(QApplication::translate("secDialog", "Phone Number", 0));
        Backbutton->setText(QApplication::translate("secDialog", "Back", 0));
        insertbutton->setText(QApplication::translate("secDialog", "Save Record", 0));
        title_2->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        detaillable_2->setText(QApplication::translate("secDialog", "Airlines  Details", 0));
        fdetails->setText(QApplication::translate("secDialog", "See Flight Details", 0));
        insertflight->setText(QApplication::translate("secDialog", "Insert Flights Details", 0));
        Backdeatail->setText(QApplication::translate("secDialog", "BACK", 0));
        title_3->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        detaillable_3->setText(QApplication::translate("secDialog", "Airlines  Details", 0));
        label_3->setText(QApplication::translate("secDialog", "  Enter the Flight Details", 0));
        search->setText(QApplication::translate("secDialog", "Search", 0));
        back->setText(QApplication::translate("secDialog", "Back", 0));
        label_4->setText(QApplication::translate("secDialog", "  Flight Name", 0));
        label_5->setText(QApplication::translate("secDialog", "  Flight Number", 0));
        label_6->setText(QApplication::translate("secDialog", "  Departure", 0));
        label_7->setText(QApplication::translate("secDialog", "  Arrive", 0));
        label_8->setText(QApplication::translate("secDialog", "  Time", 0));
        title_4->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        time->setText(QApplication::translate("secDialog", "  Time", 0));
        fnumber->setText(QApplication::translate("secDialog", "  Flight Number", 0));
        form->setText(QApplication::translate("secDialog", "  Departure", 0));
        to->setText(QApplication::translate("secDialog", "  Arrived To", 0));
        detaillable_4->setText(QApplication::translate("secDialog", "Airlines  Details", 0));
        back_2->setText(QApplication::translate("secDialog", "Back", 0));
        fname->setText(QApplication::translate("secDialog", "  Flight Name", 0));
        detaillable_5->setText(QApplication::translate("secDialog", "Enter the Details to save In Records ", 0));
        back_3->setText(QApplication::translate("secDialog", "Save", 0));
        detaillable_6->setText(QApplication::translate("secDialog", "    Ticket Cancellation ", 0));
        Title5->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        MiniTitle->setText(QApplication::translate("secDialog", "  Enter the Customer Name To Cancel Tikect", 0));
        Search->setText(QApplication::translate("secDialog", "Click Here", 0));
        Ticket->setText(QApplication::translate("secDialog", "  Ticket No:", 0));
        CName->setText(QApplication::translate("secDialog", "  Customer  Name", 0));
        CEmail->setText(QApplication::translate("secDialog", "  Customer Email", 0));
        CPassport->setText(QApplication::translate("secDialog", "  PassPort Number", 0));
        label_13->setText(QApplication::translate("secDialog", " <<<<<<<Detail Of Cancel Ticket >>>>>>>>>", 0));
        CAddress->setText(QApplication::translate("secDialog", "  Current Address", 0));
        CPhone->setText(QApplication::translate("secDialog", "  Phone Number", 0));
        CArrrival->setText(QApplication::translate("secDialog", "  Arrival City", 0));
        CTIme->setText(QApplication::translate("secDialog", "  Time of Flight", 0));
        Cdeparture->setText(QApplication::translate("secDialog", "  Departure City", 0));
        Deletecancel->setText(QApplication::translate("secDialog", "Delete", 0));
        CDate->setText(QApplication::translate("secDialog", "  Date", 0));
        Back->setText(QApplication::translate("secDialog", "Back", 0));
        detaillable_7->setText(QApplication::translate("secDialog", "    Ticket Receipt Center", 0));
        Title5_2->setText(QApplication::translate("secDialog", "Welcome To AirWays  System", 0));
        SearchReceipt->setText(QApplication::translate("secDialog", " Enter Customer Name for Receipt:", 0));
        ticketl->setText(QApplication::translate("secDialog", "  Customer Ticket No:", 0));
        Namel->setText(QApplication::translate("secDialog", "  Customer Name:", 0));
        Arrivel->setText(QApplication::translate("secDialog", "  Arrived City", 0));
        TimeL->setText(QApplication::translate("secDialog", "  Time To Departure", 0));
        departureL->setText(QApplication::translate("secDialog", "  Departure City", 0));
        DateL->setText(QApplication::translate("secDialog", "  Date To Departure", 0));
        AmountL->setText(QApplication::translate("secDialog", "  Total Amount", 0));
        Search_2->setText(QApplication::translate("secDialog", "Search", 0));
        Print->setText(QApplication::translate("secDialog", "Print", 0));
        BackR->setText(QApplication::translate("secDialog", "Back", 0));
    } // retranslateUi

};

namespace Ui {
    class secDialog: public Ui_secDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SECDIALOG_H
